import { Geist, Geist_Mono, EB_Garamond, Lato } from "next/font/google";
import "./globals.css";
import StoreProvider from "./_components/StoreProvider";
import Head from "next/head";

const garamondFont = EB_Garamond({
  variable: '--font-eb-garamond',
  subsets: ['latin'],
  weight: '600',
})

const latoFont = Lato({
  subsets:['latin'],
  
  weight: '700',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoreProvider>
          <div className="content">
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
